services:
  app:
    build:
      context: ../backend
      dockerfile: ../docker/Dockerfile
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: mysql://user:password@db:3306/url_shortener
    depends_on:
      - db
    volumes:
      - ../backend:/app
      - /app/node_modules
    command: npm run dev

  db:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: url_shortener
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3307:3306"
    volumes:
      - db-data:/var/lib/mysql

volumes:
  db-data: